constants:
  file:
    directory: D:\student\backend\upload

Spring:
  application:
    name: gallery

  datasource:
    url: jdbc:mariadb://localhost/gallery
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
